on:
  pull_request:
  push:
    branches: ['main']
    tags: ['v*']

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  docker:
    permissions:
      contents: read
      packages: write
      security-events: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/docker-ci.yaml@764c7aee28d4145c8b84d8c550727a6924a96c7e # v2.0.25
    with:
      push: ${{ github.event_name != 'pull_request' }}
